# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop before building -- they change often
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.20

# Mod Properties
mod_version=1.0.0
maven_group=net.voidstalker
archives_base_name=void-stalker

# Dependencies
fabric_api_version=0.154.0+26.2
