#!/bin/sh
# Placeholder wrapper script. In a real project this is generated by
# running `gradle wrapper` once with a local Gradle install, which writes
# gradlew, gradlew.bat, and gradle/wrapper/gradle-wrapper.jar + .properties.
# Since this sandbox has no network access to fetch that jar, generate it
# yourself the first time you open this project:
#   gradle wrapper --gradle-version 9.5.1
echo "Run: gradle wrapper --gradle-version 9.5.1   (see comment in this file)"
